source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'CYLibsPod_Example', :exclusive => true do
  pod "CYLibsPod", :path => "../"
end

target 'CYLibsPod_Tests', :exclusive => true do
  pod "CYLibsPod", :path => "../"

  pod 'FBSnapshotTestCase'
end
